### ISSUE TITLE
spark-defaults.conf file is missing

### ISSUE THREAD

**Issue by YannickLecroart21** [redaER7/Custom-Spark#1]
The spark-defaults.conf is missing so building the image fails in docker:

`ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref baed705e-7824-4d95-8158-5afc310aa0e9::nda9epo2ymzvayaerlbzrjeqo: "/spark-defaults.conf": not found`

Could you please add this file into the repository?

Thanks in advance.

**Comment by redaER7** [comment]
Thanks,
spark-defaults.conf is added

**Comment by redaER7** [comment]
Merged
